// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKlEZlJYakzbDDRb477c_UeS1ccvloaQI',
    appId: '1:578827081661:web:c6b1e54eb261fada6ce4d4',
    messagingSenderId: '578827081661',
    projectId: 'infolibra',
    authDomain: 'infolibra.firebaseapp.com',
    storageBucket: 'infolibra.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_1LfznsLiHpE0ZR8zInOYlp40G02XGOQ',
    appId: '1:578827081661:android:718c03825e7ee8a76ce4d4',
    messagingSenderId: '578827081661',
    projectId: 'infolibra',
    storageBucket: 'infolibra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKGeFvFUFT_ARkZD8zBJUbyAi-Ppux0UM',
    appId: '1:578827081661:ios:51411f75b44367666ce4d4',
    messagingSenderId: '578827081661',
    projectId: 'infolibra',
    storageBucket: 'infolibra.appspot.com',
    iosBundleId: 'com.example.infolibra',
  );
}
